sudo: false
branches:
  only:
    - master
addons:
  apt_packages:
    - lib32stdc++6
    - zip
env:
  - SMVERSION=1.9
before_script:
  - 'SHORT_COMMIT=$(git log --format=%h -1)'
  - 'git clone https://github.com/splewis/sm-builder'
  - 'cd sm-builder'
  - 'git reset --hard aa27ee36d56f0f521702f07e4502fa27fc2d0b2c'
  - 'pip install --user -r requirements.txt'
  - 'python setup.py install --prefix=~/.local'
  - 'cd .. && mkdir sm && cd sm/'
  - 'SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMVERSION}"'
  - 'wget $SMPACKAGE && tar xfz $(basename $SMPACKAGE)'
  - 'cd addons/sourcemod/scripting/'
  - 'chmod +x spcomp'
  - 'PATH+=":$PWD"'
  - 'cp -R ../../../../gameserver/scripting/include/* include/'
  - 'cd ../../../..'
script:
  - 'smbuilder --flags="-E"'
notifications:
  email: true
before_deploy:
  - 'mkdir rev$TRAVIS_BUILD_NUMBER'
  - 'mkdir -p builds/sourceadmin/addons/sourcemod/scripting/include'
  - 'cp -R gameserver/scripting/include/* builds/sourceadmin/addons/sourcemod/scripting/include'
  - 'cp -R gameserver/configs/ gameserver/translations/ builds/sourceadmin/addons/sourcemod'
  - 'cd builds'
  - 'find sourceadmin/ -printf "%P\n" | tar -cvzf ../rev$TRAVIS_BUILD_NUMBER/sourceadmin-game-$SHORT_COMMIT.tar.gz --no-recursion -C sourceadmin/ -T -'
  - 'zip -r ../rev$TRAVIS_BUILD_NUMBER/sourceadmin-game-$SHORT_COMMIT.zip sourceadmin/*'
  - 'cd ..'
  - 'cp README.md LICENSE webserver/'
  - 'find webserver/ -printf "%P\n" | tar -cvzf rev$TRAVIS_BUILD_NUMBER/sourceadmin-web-$SHORT_COMMIT.tar.gz --no-recursion -C webserver/ -T -'
  - 'zip -r rev$TRAVIS_BUILD_NUMBER/sourceadmin-web-$SHORT_COMMIT.zip webserver/*'
deploy:
  - provider: s3
  - access_key_id: AKIAIAOWUKZEVXUK2FCQ
  - secret_access_key:
    - secure: ub81bMJn4Wb4jq1dOR4B1kDsBrzT2uJTRQv2R7Izj7KxU+ldzJobsZODJJslgCDqrgzOR7VIrN7E4rpSVSBhbmgkWuis4dBR7OXB1x5DQncbs2/WUS6R4a4FqukQ1+pnOnrjXTXS4Uv1BvAphNNHq60dCJ/L99F93Cz4RNZczvdTeiAqAybbLHJC/JgXNOhsV+6buwxd0sYQrHBdqZGFFRCt9smD6oWWiLWg1jyqGadtRg1vVKFe3kBSc1ejpgFih+z71d/N9cAW3Y87UD+LsNGUDEHtUMb6neVmIpgnoP6+uMcscu2fMGVO1JVOkctOFu7oaosZ1ShUBb+Sclu4shFW1M3laVWB4aWl5OfvTGr30cOu9bIgh84srsUta1n8PACwzZafy0G14nj2RQN3NzAM05H8+UJicHb7i34TVrRwujqFj3VpUPdVQPXVGpmCbQeHnoUev9izIUvI65D4ApCSAGO7yWTYelYQKclu1+n7OtaOnllvCFYokKiskhwpwEg8uvOGlXFJ1r4wWYJJSEHRGcpjOYfD/9w7KVUANOcUttC3C5Nb1Q1yfk07AgoQbM9sPYwUJ9epTIqnIgRuNY/qcNlJMPoiSe1Rtlkg4U5AFAWMSMoBGVSu0LxTM8EID14U/WRMrBIW701T3Uby8FUkLNbtmJaEQvVj6pFitQs=
  - bucket: sourceadmin-builds
  - local_dir: rev$TRAVIS_BUILD_NUMBER
  - acl: public_read
  - skip_cleanup: true
  - on:
    - repo: Technoblazed/sourceadmin
